environment:
  global:
    RUSTFLAGS: -Zunstable-options -Ctarget-feature=+crt-static
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      DEPLOY: 1

install:
  # Install rust, x86_64-pc-windows-msvc host
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain nightly
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --locked
  - cargo build --release

before_deploy:
  - ps: |
        $NAME = "cargo-vendor-${env:APPVEYOR_REPO_TAG_NAME}-${env:TARGET}"
        New-Item -Path $NAME -ItemType directory
        Copy-Item target/release/cargo-vendor.exe "${NAME}/"
        Copy-Item LICENSE-MIT "${NAME}/"
        Copy-Item LICENSE-APACHE "${NAME}/"
        Copy-Item README.md "${NAME}/"
        7z a -ttar "${NAME}.tar" "${NAME}"
        7z a "${NAME}.tar.gz" "${NAME}.tar"
        Push-AppveyorArtifact "${NAME}.tar.gz"

deploy:
  artifact: /.*\.tar.gz/
  auth_token:
    secure: nHB4fVo+y/Aak+L0nYfrT8Rcs8OfUNm0F2xcIVFVYJ9ehf0CzvCmSMUvWguM0kKp
  description: ''
  on:
    appveyor_repo_tag: true
  provider: GitHub

